# Generated by Django 4.2.7 on 2023-11-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("size", models.FloatField()),
                ("length_seconds", models.IntegerField()),
                ("user_id", models.CharField(max_length=100)),
            ],
        ),
    ]
