# Generated by Django 4.2.7 on 2023-11-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0003_alter_video_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="duration_secs",
        ),
        migrations.RemoveField(
            model_name="video",
            name="size",
        ),
        migrations.RemoveField(
            model_name="video",
            name="time",
        ),
        migrations.RemoveField(
            model_name="video",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="video",
            name="video_name",
        ),
        migrations.AlterField(
            model_name="video",
            name="location",
            field=models.FileField(upload_to="uploads/%Y/%m/%d"),
        ),
    ]
