# Generated by Django 4.2.7 on 2023-11-17 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="length_seconds",
            new_name="duration_secs",
        ),
        migrations.AddField(
            model_name="video",
            name="time",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
