# Generated by Django 4.2.7 on 2023-12-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0006_video_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_url",
            field=models.TextField(),
        ),
    ]
