# Generated by Django 4.2.7 on 2023-12-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0008_alter_video_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="user",
            field=models.CharField(default="test", max_length=100),
        ),
    ]
