# Generated by Django 4.2.7 on 2023-12-19 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("video_processor", "0009_video_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
