# Generated by Django 4.2.7 on 2023-12-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0013_rename_location_video_filesystem_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="level",
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="number_of_uploads",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
