# Generated by Django 4.2.7 on 2023-12-21 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0016_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="subscription",
        ),
    ]
