# Generated by Django 4.2.7 on 2023-12-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0017_remove_userprofile_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="highlights",
            field=models.FileField(default=1, upload_to="uploads/%Y/%m/%d"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="smashes",
            field=models.FileField(upload_to="uploads/%Y/%m/%d"),
        ),
    ]
