# Generated by Django 4.2.7 on 2023-12-21 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("video_processor", "0018_userprofile_highlights_alter_userprofile_smashes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="highlights",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="smashes",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profileUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videoUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="smashes",
            field=models.ManyToManyField(to="video_processor.video"),
        ),
    ]
