# Generated by Django 4.2.7 on 2023-12-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "video_processor",
            "0022_userprofile_highlights_remove_userprofile_smashes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="level",
            field=models.FloatField(default=1.0),
        ),
    ]
