# Generated by Django 4.2.7 on 2024-01-18 14:46

from django.db import migrations, models
import video_processor.models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0023_alter_userprofile_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="number_of_uploads",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="players",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="video",
            name="filesystem_url",
            field=models.FileField(upload_to=video_processor.models.user_upload_path),
        ),
    ]
