# Generated by Django 3.2.23 on 2024-01-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0024_alter_userprofile_number_of_uploads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='filesystem_url',
            field=models.FileField(upload_to=''),
        ),
    ]
