# Generated by Django 3.2.23 on 2024-01-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0025_alter_video_filesystem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='web_url',
            field=models.URLField(max_length=500),
        ),
    ]
