# Generated by Django 5.0.2 on 2024-02-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0027_task_userprofile_tasks_in_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="estimated_time",
            field=models.FloatField(default=0.0),
        ),
    ]
