# Generated by Django 5.0.2 on 2024-02-28 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0028_task_estimated_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imageUser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_identifier", models.CharField(max_length=100)),
                ("extracted_speeds", models.JSONField()),
                (
                    "group_highlight",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groupHighlight",
                        to="video_processor.video",
                    ),
                ),
                ("player_frames", models.ManyToManyField(to="video_processor.image")),
                (
                    "smashes",
                    models.ManyToManyField(
                        related_name="smashes", to="video_processor.video"
                    ),
                ),
            ],
        ),
    ]
