# Generated by Django 5.0.2 on 2024-03-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0029_image_taskresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskresult",
            name="extracted_speeds",
            field=models.JSONField(default=dict),
        ),
    ]
