# Generated by Django 5.0.2 on 2024-03-02 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0030_alter_taskresult_extracted_speeds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskresult",
            name="group_highlight",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groupHighlight",
                to="video_processor.video",
            ),
        ),
    ]
