# Generated by Django 5.0.2 on 2024-03-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0031_alter_taskresult_group_highlight"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskresult",
            name="timestamp",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
