# Generated by Django 5.0.2 on 2024-03-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0032_taskresult_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="timestamp_string",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
