# Generated by Django 5.0.2 on 2024-03-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0033_video_timestamp_string"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="video",
            name="web_url",
            field=models.URLField(max_length=1000),
        ),
    ]
