# Generated by Django 5.0.2 on 2024-03-12 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0035_task_thumbnail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskresult",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taskResultUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
