# Generated by Django 5.0.2 on 2024-03-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0036_taskresult_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="subscription",
            field=models.CharField(default="", max_length=100),
        ),
    ]
