# Generated by Django 5.0.2 on 2024-04-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0037_userprofile_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
