# Generated by Django 5.0.2 on 2024-04-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0038_task_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
