# Generated by Django 5.0.2 on 2024-04-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0039_image_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="pipeline_stage",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
