# Generated by Django 4.2.7 on 2023-11-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "video_processor",
            "0002_rename_length_seconds_video_duration_secs_video_time",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="location",
            field=models.FileField(upload_to="uploads"),
        ),
    ]
