# Generated by Django 4.2.7 on 2023-12-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0005_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_url",
            field=models.URLField(default="test"),
        ),
    ]
