# Generated by Django 4.2.7 on 2023-12-21 02:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0012_video_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="location",
            new_name="filesystem_url",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="video_url",
            new_name="web_url",
        ),
    ]
