# Generated by Django 4.2.7 on 2023-12-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0014_userprofile_level_userprofile_number_of_uploads"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="players",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="smashes",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
