# Generated by Django 4.2.7 on 2023-12-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0019_remove_userprofile_highlights_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="highlights",
            field=models.ManyToManyField(
                related_name="highlights_videos", to="video_processor.video"
            ),
        ),
    ]
