# Generated by Django 4.2.7 on 2023-12-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0020_userprofile_highlights"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="highlights",
        ),
        migrations.AddField(
            model_name="video",
            name="type",
            field=models.CharField(
                choices=[
                    ("raw", "Raw"),
                    ("smash", "Smash"),
                    ("highlight", "Highlight"),
                ],
                default="raw",
                max_length=10,
            ),
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="smashes",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="smashes",
            field=models.FileField(default=1, upload_to="uploads/%Y/%m/%d"),
            preserve_default=False,
        ),
    ]
