# Generated by Django 4.2.7 on 2023-12-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processor", "0021_remove_userprofile_highlights_video_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="highlights",
            field=models.ManyToManyField(
                related_name="highlights_videos", to="video_processor.video"
            ),
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="smashes",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="smashes",
            field=models.ManyToManyField(to="video_processor.video"),
        ),
    ]
